title: TXST Business AI Lab
description: Exploring the intersection of AI and Business at Texas State University.
theme: jekyll-theme-cayman
show_downloads: false

# Optional - this enables clean URLs like /about instead of /about.html
permalink: pretty
